<?php $urlClassInfo = Mage::getModel('adminhtml/url')->getUrl('*/*/classinfo'); ?>
        $('class_select').observe('change', function(e){			
			if($('class_select').value) {
				var r = new Ajax.Request('<?php  echo $urlClassInfo; ?>',{
					method:'get',
					parameters:{class : $('class_select').value,
                                sort  : $('sort_select').value,
                                type  : 'Helper'},
					onSuccess:function(r){
						$('result').innerHTML = r.responseText;
					}
				})
			}
		});