<?php
$urlNamespace = Mage::getModel('adminhtml/url')->getUrl('*/*/namespaces');
$urlClassInfo = Mage::getModel('adminhtml/url')->getUrl('*/*/classinfo');
?>
<script type="text/javascript">
	document.observe("dom:loaded", function() {
		$('codepool_select').observe('change',function(e){			
			if($('codepool_select').value) {
				var r = new Ajax.Request('<?php  echo $urlNamespace; ?>',{
					method:'get',
					parameters:{codepool : $('codepool_select').value},
					onSuccess:function(r){
						$('namespace_select').innerHTML = r.responseText;
						$('namespace_span').show();
                        $('module_span').hide();
                        $('class_span').hide();
					}
				})
			}
		});
		
        <?php echo $this->getChildHtml('js_observer_namespaces'); ?>
		
        <?php echo $this->getChildHtml('js_observer_modules'); ?>
        
        <?php echo $this->getChildHtml('js_observer_classes'); ?>

        /*
		$('class_select').observe('change', function(e){			
			if($('class_select').value) {
				var r = new Ajax.Request('<?php  //echo $urlClassInfo; ?>',{
					method:'get',
					parameters:{class : $('class_select').value,
                                sort : $('sort_select').value},
					onSuccess:function(r){
						$('result').innerHTML = r.responseText;
					}
				})
			}
		});
        */
        
        $('sort_select').observe('change', function(e){			
			if($('helper_select').value) {
				var r = new Ajax.Request('<?php  echo $urlClassInfo; ?>',{
					method:'get',
					parameters:{class : $('helper_select').value,
                                sort : $('sort_select').value},
					onSuccess:function(r){
						$('result').innerHTML = r.responseText;
					}
				})
			}
		});
        
        showIsHide = function(el)
        {
            $(el).toggle();
            return false;
        };
		
		moreIsLess = function(el, caller)
		{
			$(el).toggle();
			$(caller).innerHTML == 'more...' ? $(caller).innerHTML = 'less...' : $(caller).innerHTML = 'more...';
			return false;
		};
	});
</script>